[config]
skip_core_tasks = true

[env]
PROFILE = "release"
TARGET_DIR = "./target"
BUILD_ARTIFACT_NAME = "${CARGO_MAKE_CRATE_NAME}"
BUILD_OUTPUT_DIR = "./wasm-target"
BINDGEN_TARGET_DIR_NAME = "wasm-bindgen-target"

[tasks.format]
description = "Run rustfmt"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean-wasm]
description = "Delete the wasm-target directory"
script_runner = "@shell"
script = '''
rm -rf ${BUILD_OUTPUT_DIR}
'''

[tasks.clean]
description = "Clean build files and wasm-target directory"
dependencies = ["clean-wasm"]
command = "cargo"
args = ["clean"]

[tasks.run-cargo-build]
description = "Build the wasm binary"
command = "cargo"
args = [
    "build",
    "--profile",
    "${PROFILE}",
    "--target",
    "wasm32-unknown-unknown",
    "--target-dir",
    "${TARGET_DIR}",
]

[tasks.build-wasm-bin]
description = "Build & link the wasm binary into a playable web-page"
dependencies = ["clean-wasm", "run-cargo-build"]
install_crate = "wasm-bindgen-cli"
command = "wasm-bindgen"
args = [
    "--out-name",
    "generated",
    "--out-dir",
    "${BUILD_TARGET_DIR}/${BINDGEN_TARGET_DIR_NAME}",
    "--target",
    "web",
    "${BUILD_TARGET_DIR}/${BUILD_ARTIFACT_NAME}.wasm",
]

[tasks.run-opt]
condition = { env_set = ["RUN_OPTIMIZATION"] }
description = "Generate an optimized version of the wasm binary"
dependencies = ["build-wasm-bin"]
install_crate = "wasm-opt"
command = "wasm-opt"
args = [
    "-Oz",
    "--output",
    "${BUILD_TARGET_DIR}/${BINDGEN_TARGET_DIR_NAME}/optimized_bg.wasm",
    "${BUILD_TARGET_DIR}/${BINDGEN_TARGET_DIR_NAME}/generated_bg.wasm",
]

[tasks.copy-opt]
condition = { env_set = ["RUN_OPTIMIZATION"] }
description = "Generate optimized wasm binary and replace the old binary"
dependencies = ["run-opt"]
cwd = "${BUILD_TARGET_DIR}/${BINDGEN_TARGET_DIR_NAME}"
script_runner = "@shell"
script = "mv ./optimized_bg.wasm ./generated_bg.wasm"

[tasks.copy-files]
description = "Copy static site files & assets into the wasm-target directory"
dependencies = ["copy-opt"]
script_runner = "@shell"
script = '''
mkdir -p ${BUILD_OUTPUT_DIR}/target
cp -r ./src/site/* ${BUILD_OUTPUT_DIR}/
cp -r ./assets ${BUILD_OUTPUT_DIR}/
cp ${BUILD_TARGET_DIR}/${BINDGEN_TARGET_DIR_NAME}/generated_bg.wasm ${BUILD_OUTPUT_DIR}/target/
cp ${BUILD_TARGET_DIR}/${BINDGEN_TARGET_DIR_NAME}/generated.js ${BUILD_OUTPUT_DIR}/target/
'''

[tasks.build]
env = { "BUILD_TARGET_DIR" = "${TARGET_DIR}/wasm32-unknown-unknown/${PROFILE}" }
description = "Run full build process and put output in wasm-target directory"
run_task = "copy-files"

[tasks.build-release]
env = { "PROFILE" = "release-wasm", "RUN_OPTIMIZATION" = "1" }
description = "Build an optimized release version of the game"
run_task = "build"

[tasks.default]
run_task = "build"

[tasks.serve]
description = "Build and serve a copy of the playable page"
dependencies = ["build"]
install_crate = "basic-http-server"
command = "basic-http-server"
args = ["./wasm-target"]
